Models/functions/Reports.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StudentFinanceSupport.Models.functions
{
    public class Reports
    {
        //valid dates
        //2015
        //06/2015
        //09/06/2015
        
        public string date_type { get; set; }
        public string gender { get; set; }
        //\d{0,2}\/\d{0,2}\/\d{0,4}|\d{0,2}\/\d{0,4}|
        [Display(Name = "Date")]
        [RegularExpression(@"\d{0,2}\/\d{0,2}\/\d{0,4}|\d{0,2}\/\d{4}|\s*\d{4}", ErrorMessage = "Date must be in the following format dd/mm/yyyy or mm/yyyy or yyyy")]
        //[RegularExpression("\\d{0,4}", ErrorMessage = "Date must be in the following format dd/mm/yyyy or mm/yyyy or yyyy bbbb")]
        public string start_date { get; set; }

        public string Ethnicity { get; set; }
        public int? Faculity { get; set; }

        [Display(Name = "Student Age")]
        [RegularExpression("^(0?[1-9]|[1-9][0-9])$", ErrorMessage = "Must be a age number eg. 21")]
        public int? student_age { get; set; }

        public int? Campus { get; set; }
        public int? GrantType { get; set; }
       
        public DateTime getBirthYear()
        {
            //minus todays date eg 2015 - 15 = born 2000
            int theAge = Convert.ToInt32(student_age) * -1;
            
            DateTime theDate = DateTime.Now.AddYears(theAge);
            return theDate;
        }
        public DateTime getDate()
        {
            //need to check if date valid
            string theFormat = "dd/MM/yyyy";
            switch (this.date_type.ToLower())
            {
                case "month":
                    theFormat = "MM/yyyy";
                    break;
                case "year":
                    theFormat = " yyyy";
                    break;
            }
            DateTime theDate;
            DateTime.TryParseExact
                  (this.start_date,
                   theFormat,
                   CultureInfo.InvariantCulture,
                   DateTimeStyles.None,
                   out theDate);

            return theDate;
        }
    }
}

Controllers/StudentVouchersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentFinanceSupport.Models;
using StudentFinanceSupport.Helpers;

namespace StudentFinanceSupport.Controllers
{
    [Authorize(Roles = "Admin,Advisor")]
    public class StudentVouchersController : BaseController
    {
        

        // GET: StudentVouchers
        public ActionResult Index(string message)
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            var studentVouchers = db.StudentVouchers.Include(s => s.StudentRegistration);
            ViewBag.message = message;
            return View(studentVouchers.ToList());
        }

        public ActionResult byStudentID(string id)
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            

            var theVouchers = (from a in db.StudentVouchers
                               where a.student_ID == id
                               select a.id_student_vouchers
                               ).FirstOrDefault();

            if (theVouchers == null)
                return RedirectToAction("Error", new { message = "Invalid student details." });
            //var other_grants = db.StudentVouchers.Where(a => a.student_ID == studentVoucher.student_ID);

            //studentVoucher.student_ID
            return RedirectToAction("Details", new { id = theVouchers });
        }
        // GET: StudentVouchers/Details/5
        //_student_vouchers
        
        public ActionResult StudentVouchersAll(string id)
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            IEnumerable<StudentVoucher> studentVouchers = db.StudentVouchers.Where(a => a.student_ID == id).ToList();

            if (studentVouchers == null)
                return RedirectToAction("Error", new { message = "Invalid student details." });

            return View(studentVouchers);
        }
        public ActionResult Details(int id)
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
         


            StudentVoucher studentVoucher = db.StudentVouchers.Find(id);
            if (studentVoucher == null)
                return RedirectToAction("Error", new { message = "Invalid student details." });


            var pmViewModel = new ProfileUserViewModel
            {
                UserGrant = studentVoucher,
                UserGrantList = db.StudentVouchers.Where(a => a.student_ID == studentVoucher.student_ID)
            };

            //var other_grants = db.StudentVouchers.Where(a => a.student_ID == studentVoucher.student_ID);

            //studentVoucher.student_ID
            return View(pmViewModel);
        }

        // GET: StudentVouchers/Add
        public ActionResult Add(String id)
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            StudentVoucher studentVoucher = new StudentVoucher();
            //voucher.GrantType = db.GrantTypes.ToList();
            //parsing to the view
            //ViewBag.GrantType = Helpers.Helpers.GrantTypes();
            ViewBag.grant_type_id = db.GrantTypes;
            
            // new SelectList(db.GrantTypes, "grant_type_id", "grant_name");
            //ViewBag.grant_type_id = new SelectList(db.GrantTypes, "grant_type_id", "grant_name");
            ViewBag.student_ID = (id != null) ? id : String.Empty;
            studentVoucher.grant_type_id = 0;
            return View(studentVoucher);
        }

        // POST: StudentVouchers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Include = "student_ID,GrantDescription,GrantValue,DateOfIssue,KuhaFunds,grant_type_id")] StudentVoucher studentVoucher)
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            //lets make sure student exists
            if (this.studentExists(studentVoucher.student_ID) == false)
            {
                ModelState.AddModelError("Student_ID", "Student ID Does Not Exist");
                //return View(StudentRegistration);
            }

            //check the required grant requirements have been meet
            GrantType GrantType = db.GrantTypes.Find(studentVoucher.grant_type_id);

           if (GrantType.grant_description == true && (String.IsNullOrEmpty(studentVoucher.GrantDescription)))
               ModelState.AddModelError("GrantDescription", "Grant description must contain details it is required");


           if (GrantType.grant_value == true && studentVoucher.GrantValue <= 0)
               ModelState.AddModelError("GrantValue", "GrantValue needs to be greater than 0");

            
            if (ModelState.IsValid)
            {
                db.StudentVouchers.Add(studentVoucher);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            //pass back our data
            ViewBag.grant_type_id = db.GrantTypes;
            ViewBag.student_ID = (studentVoucher.student_ID != null) ? studentVoucher.student_ID : String.Empty;

            return View(studentVoucher);
        }
        public JsonResult studentSearch(string query)
        {
            //search for a student by name or id & last name
            if (String.IsNullOrWhiteSpace(query))
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            var result = from student in db.StudentRegistrations
                         where
                             student.Student_ID.StartsWith(query) ||
                             student.FirstName.Contains(query) ||
                             student.LastName.Contains(query)
                         select new
                             {
                                 student_id = student.Student_ID,
                                 student_name = student.FirstName + " " + student.LastName
                             };

            //only show 10 results max
            return Json(result.Take(10), JsonRequestBehavior.AllowGet);
        }
        

        // GET: StudentVouchers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            StudentRegistrationsModel db = new StudentRegistrationsModel();
           
            
            int id_student_vouchers;
            int.TryParse(id, out id_student_vouchers);
            //var theStudent = (from student in db.StudentVouchers where student.id_student_vouchers == id_student_vouchers select student);
            StudentVoucher theStudent = db.StudentVouchers.Find(id_student_vouchers);
            
            if (theStudent == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            ViewBag.student_ID = theStudent.student_ID;
            //ViewBag.GrantType = Helpers.Helpers.GrantTypes();
            //ViewBag.GrantType = new SelectList(Helpers.Helpers.GrantTypes(), "Value", "Text", theStudent.GrantType);
            //ViewBag.GrantType = theStudent.GrantType;
            ViewBag.grant_type_id = db.GrantTypes;

                //new SelectList(db.StudentRegistrations, "Student_ID", "FirstName", studentVoucher.student_ID);
            return View(theStudent);
        }

        // POST: StudentVouchers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_student_vouchers,student_ID,GrantDescription,GrantValue,DateOfIssue,KuhaFunds,grant_type_id")] StudentVoucher studentVoucher)
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            if (ModelState.IsValid)
            {
                StudentVoucher theVoucher = db.StudentVouchers.Find(studentVoucher.id_student_vouchers);
                theVoucher.KuhaFunds = studentVoucher.KuhaFunds;
                theVoucher.grant_type_id = studentVoucher.grant_type_id;
                theVoucher.GrantValue = studentVoucher.GrantValue;
                theVoucher.GrantDescription = studentVoucher.GrantDescription;
                theVoucher.DateOfIssue = studentVoucher.DateOfIssue;

               // db.StudentVouchers.Add(theVoucher);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.grant_type_id = db.GrantTypes;
            //ViewBag.student_ID = new SelectList(db.StudentRegistrations, "Student_ID", "FirstName", studentVoucher.student_ID);
            return View(studentVoucher);
        }

        // GET: StudentVouchers/Delete/5
        public ActionResult Delete(int id)
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentVoucher studentVoucher = db.StudentVouchers.Find(id);
            if (studentVoucher == null)
            {
                return HttpNotFound();
            }
            return View(studentVoucher);
        }

        // POST: StudentVouchers/Delete/5
        //[HttpPost, ActionName("Delete")]
       // [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

Views/Reports/ReportFilter.cshtml
@using StudentFinanceSupport.Helpers;
@Styles.Render("~/Content/Wizard")
@Scripts.Render("~/bundles/wizardSteps")
<style>
    .wizard > .content > .body {
        height: 300px;
    }
    .tabcontrol > .content {
        height: 12em;
        padding-top: 5px; 
    }
    #report-btn-group btn {
        display: inline-block;
    }
    #report-btn-group {
        width :350px;
    }
    #search_report_form{
         height:350px;
         min-width: 825px;
    }

   
</style>
<div id="search_report_form" class="" style="">
    <div class="panel panel-primary">
        <div class="panel-heading">
            Report Filters
        </div>
        <div id="filter_wizard" class="panel-body">
            <h3>Report Dates</h3>
            <section id="view_by" class="">
               
                <div class="form-group">
                    <div class="col-md-8">
                        <div id="select_date_type">
                            Report Type
                            @Html.DropDownList(
                                   "date_type",
                                    Helpers.DayWeekMonthYearSelect(), Helpers.SelectOneSpacer,
                                new { @class = "form-control", data_placeholder = "Choose a View..." })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-8">
                        <div id="select_date">

                            Date
                            @Html.TextBox("start_date", @DateTime.Now.ToShortDateString(), htmlAttributes: new { @class = "datepicker form-control" })

                        </div>
                    </div>
                </div>
                </section>
                
            <h3>Campus Filters</h3>
                <section>
                <div class="form-group">


                    <div class="col-md-8">
                        <div class="form-group">

                            <div class="col-md-10">
                                <div class="col-md-6">
                                    Campus
                                    @Html.DropDownList(
                                                        "Campus",
                                                   (IEnumerable<SelectListItem>)ViewBag.Campus, Helpers.SelectOneSpacer,
                                new { @class = "form-control", data_placeholder = "Choose a Grant..." })

                                </div>



                            </div>
                        </div>
                    </div>

                </div>

                <div class="form-group">
                    <div class="col-md-8">
                        <div class="form-group">
                            <div class="col-md-10">
                                <div class="col-md-6">
                                    Faculity
                                    @Html.DropDownList(
                                    "Faculity",
                                 (IEnumerable<SelectListItem>)ViewBag.Faculity, Helpers.SelectOneSpacer,
                                new { @class = "form-control", data_placeholder = "Select a Faculity..." })

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <h3>Grant Types Filters</h3>
            <section>
                <div class="form-group">


                    <div class="col-md-8">
                        <div class="form-group">

                            <div class="col-md-10">
                                <div class="col-md-6">

                                    @Html.DropDownList(
                                             "GrantType",
                                          (IEnumerable<SelectListItem>)ViewBag.GrantType, Helpers.SelectOneSpacer,
                                new { @class = "form-control", data_placeholder = "Select a Faculity..." })

                                   

                                </div>



                            </div>
                        </div>
                    </div>

                </div>
            </section>
            <h3>Student Filters</h3>
            <section>
                <div class="form-group">


                    <div class="col-md-8">
                        <div class="form-group">

                            <div class="col-md-10">
                                <div class="col-md-6">
                                    Gender
                                    @Html.DropDownList(
                                                         "gender",
                                                         Helpers.DropDownGender(), Helpers.SelectOneSpacer,
                                new { @class = "form-control", data_placeholder = "Choose a Gender..." })

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="form-group">

                            <div class="col-md-10">
                                <div class="col-md-6">
                                    Age
                                    @Html.TextBox("student_age", null, htmlAttributes: new { @class = "form-control", @placeholder = "Age" })
                                </div>
                                <div class="col-md-6">
                                    Ethnicity
                                    @Html.DropDownList(
                                                        "Ethnicity",
                                                         Helpers.Ethnicity(), Helpers.SelectOneSpacer,
                                new { @class = "form-control", data_placeholder = "Choose a Gender..." })
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </section>

            <h3>Saved Filters</h3>
            <section>
                <div class="form-group">


                    <div class="col-md-8">
                        <div class="form-group">

                            <div class="col-md-10">
                                <div class="col-md-6">
                                    Sorry not implmented

                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </section>
        </div>
       
    </div>
    <!-- /.col-lg-4 -->
    <div class="form-group pull-left col-md-10" style="bottom:15px;right:30px">

        <div class="col-md-2 ">
            <span id="report-btn-group" style="display:inline-block">
                <button id="search_report_reset_btn" class="btn btn-warning">Reset Filters</button>
                <button id="search_report_btn" class="btn btn-success">Generate Report</button>
            </span>
        </div>

    </div>
</div>

<script>
    //generate report

    $(document).ready(function () {     //Specify our form area as this is partial view don't want any document clashes

      

       

        var calander_selections = {
            day: {
                format: "dd/mm/yyyy",
                autoclose: true,
            },
            week: {
                format: "dd/mm/yyyy",
                minViewMode: "weeks",
                viewMode: "weeks",
                autoclose: true,
                beforeShowDay: function (date) {
                    //console.log("date", date.getDay())
                    
                    return date.getDay() == 1
                }
            },
            month: {
                format: "mm/yyyy",
                minViewMode: "months",
                viewMode: "months",
                autoclose: true,
            },
            year: {
                format: " yyyy",
                viewMode: "years",
                minViewMode: "years",
                autoclose: true,
            }
        }

  


        $("#filter_wizard").steps({
            headerTag: "h3",
            bodyTag: "section",
            transitionEffect: "slideLeft",
            enableFinishButton: false,
            enablePagination: false,
            enableAllSteps: true,
            titleTemplate: "#title#",
            cssClass: "tabcontrol"

        });

        //date picker
        $('.datepicker').datepicker(calander_selections.day);

        //report selection has changed
        $("#date_type").change(function () {
            var selection = $(this).val()
            //console.log("selection", selection)
            //console.log("bin", calander_selections[selection]);
            var options = calander_selections[selection];
            $('.datepicker').datepicker('remove');
            $('.datepicker').val('')
            $('.datepicker').datepicker(options);
            $('.datepicker').datepicker("show");
        })
      
    })

</script>

Views/Reports/ViewReport.cshtml
@model IEnumerable<StudentFinanceSupport.Models.StudentVoucher>


<table class="table table-striped table-bordered table-hover" id="voucher-report-table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.DateOfIssue)</th>
            <th>@Html.DisplayNameFor(model => model.StudentRegistration.FirstName)</th>
            
            
            <th>@Html.DisplayNameFor(model => model.StudentRegistration.Campus.campus_name)</th>
            <th>@Html.DisplayNameFor(model => model.GrantType.grant_name)</th>
            <th>@Html.DisplayNameFor(model => model.GrantValue)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>


        @foreach (var student in Model)
        {
            <tr class="odd gradeX">
                <td>@Html.DisplayFor(modelItem => student.DateOfIssue)</td>
                <td>
                @Html.DisplayFor(modelItem => student.StudentRegistration.FirstName)
                @Html.DisplayFor(modelItem => student.StudentRegistration.LastName)
                </td>
               
                
                <td>@Html.DisplayFor(modelItem => student.StudentRegistration.Campus.campus_name)</td>
                <td>@Html.DisplayFor(modelItem => student.GrantType.grant_name)</td>
                <td>$@Html.DisplayFor(modelItem => student.GrantValue)</td>
                <td class="center">
                    
                        @Html.ActionLink("Edit Grant", "Edit", "StudentVouchers",
                     new { id = student.id_student_vouchers },
                            htmlAttributes: new { @class = "btn btn-default " }
                          )



                </td>

            </tr>
        }

    </tbody>
</table>


<script>
    $(document).ready(function () {
        $('#voucher-report-table').DataTable({
            responsive: true
        });
    });
</script>