Controllers/AdministratorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentFinanceSupport.Models;
using StudentFinanceSupport.Models.functions;
using System.Web.Security;
using System.Net.Mail;
using System.Net.Mime;
using System.Text.RegularExpressions;

namespace StudentFinanceSupport.Controllers
{
    public class AdministratorsController : BaseController
    {

        
        public AdministratorsController()
        {
            //list of Actions in this controller that we don't want to security check session on
            bypassAdminCheck("Administrators/Login");
            bypassAdminCheck("Administrators/ChangePassword");
            
            //bypassAdminCheck("Administrators/Login");
        }

        // GET: Administrators
       // [AuthorizeUser(AccessLevel = "CreateAdmins")]
        public ActionResult Index()
        {
            //Administrator theAdmins = new Administrator();
            //theAdmins = db.Administrators();
            
            return View();
        }

        // GET: Administrators/Add
        [Authorize(Roles = "Admin")]
        public ActionResult Admins()
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            
            return View(db.Administrators.ToList());
        }
       // [HttpPost]
        public ActionResult ChangePassword()
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            //@important don't pass the administor model for modifying ONLY the AdministratorLogin model for security as this is public

            //check if we are coming from a recovery
            if (Session["AdministratorRecovery"] != null)
            {
                //remove any logged in session
                Session.Remove("AdministratorLogin");
                
                Recovery theRecovery = (Recovery)Session["AdministratorRecovery"];
                var theAdmin = (from a in db.Administrators
                                join b in db.Recoveries on a.UserId equals b.UserId
                                where b.recovery_key == theRecovery.recovery_key
                                select a).SingleOrDefault();
                //clear the password field
                theAdmin.Password = String.Empty;
                Session["AdministratorLogin"] = theAdmin.loginDetails();
                return View(theAdmin.loginDetails());
            }

            AdministratorLogin CurrentAdmin = this.AdminSession();
            //check if we are logged in
            if (CurrentAdmin == null)
            {

                return RedirectToAction("Login");
            }

            CurrentAdmin.Password = "";
             return View(CurrentAdmin);
        }

        [HttpPost]
        public ActionResult ChangePassword(AdministratorLogin theAdmin)
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            //passing back from session so no injection of userID or email can happen we also need to clear the model state and re-validate
            ModelState.Clear();
            theAdmin.Email = this.AdminSession().Email;
            theAdmin.UserId = this.AdminSession().UserId;
            TryValidateModel(theAdmin);  

            //ModelState.Clear();
            //check password match
            if (theAdmin.Password != Request.Form["password_match"])
            {
                //clear the viewbag password so they re-type
                ViewBag.password_match = String.Empty;
                ModelState.AddModelError("Password", "Passwords don't match");
            }
            if (!ModelState.IsValid)
            {
                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        Console.Write(error);
                    }
                }
                return View(theAdmin);
            }

            //grab the current admin session and update password
            //process the update
            AdministratorLogin thisUser = this.AdminSession();

            var change = (from a in db.Administrators
                          where a.UserId == thisUser.UserId
                            select a).SingleOrDefault();
            //rehash password
            change.Password = PasswordHashing.Encrypt(theAdmin.Password);

            //clean up from recovery
            if (Session["AdministratorRecovery"] != null)
            {
                Session.Remove("AdministratorRecovery");
                //remove any recovery options that are set
                var recovery = (from b in db.Recoveries where b.UserId == change.UserId select b);
                foreach (var entry in recovery)
                    db.Recoveries.Remove(entry);
            }

            db.Entry(change).State = EntityState.Modified;
            db.SaveChanges();
 

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Add()
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            Administrator theAdmins = new Administrator();

            //theAdmins = db.Administrators();



            //var role_list = db.RoleTypes;
            //var model = new Administrator();
            //model.Roles = new SelectList(db.RoleTypes, "role_type_id", "role_name");
            ViewBag.role_type_id = new SelectList(db.RoleTypes, "role_type_id", "role_description");
            ViewBag.password_match = String.Empty;
            return View(theAdmins);
        }

        [HttpPost]
        public ActionResult Add(Administrator newAdmin)
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            //newAdmin.Roles = Request.Form["admin_roles"];

            ViewBag.role_type_id = new SelectList(db.RoleTypes, "role_type_id", "role_description");
            //ViewBag.Roles = Request.Form["admin_roles"];
            ViewBag.password_match = Request.Form["password_match"];
            
           
            //check for unique email address
            //if (ModelState.ContainsKey("Roles"))
              //  ModelState["Roles"].Errors.Clear();
            
            if (db.Administrators.Any(m => m.Email.ToLower() == newAdmin.Email.ToLower()))
            {
                ModelState.AddModelError("Email", "Admin email already exists!");
            
            }
            //check password match
            if (newAdmin.Password != Request.Form["password_match"])
            {
                //clear the viewbag password so they re-type
                ViewBag.password_match = String.Empty;
                ModelState.AddModelError("Password", "Passwords don't match");
            }

            //check mobile phone number if added

            if (!ModelState.IsValid)
            {
                return View(newAdmin);
            }

            //PasswordHashing passwordHash = new PasswordHashing();
            newAdmin.Password = PasswordHashing.Encrypt(newAdmin.Password);

            //add the admin
            db.Administrators.Add(newAdmin);
            db.SaveChanges();

            //we will now have admin id if saved
            //int theAdmin_id = newAdmin.UserId;
            //check roles that need to be added

            //store roles into a string array
            //this.addRoles(newAdmin, Request.Form["roles"]);

            
            return RedirectToAction("Admins");
        }
         [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Administrator administrator = db.Administrators.Find(id);
            if (administrator == null)
            {
                return HttpNotFound();
            }
            return View(administrator);
        }
        // GET: Administrators1/Edit/5
         [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Administrator administrator = db.Administrators.Find(id);
            if (administrator == null)
            {
                return HttpNotFound();
            }
            ViewBag.role_type_id = new SelectList(db.RoleTypes, "role_type_id", "role_name", administrator.role_type_id);
            return View(administrator);
        }

        // POST: Administrators1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,Email,Password,FirstName,LastName,mobile,role_type_id")] Administrator administrator)
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();
            if (ModelState.IsValid)
            {
                db.Entry(administrator).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Admins");
            }
            ViewBag.role_type_id = new SelectList(db.RoleTypes, "role_type_id", "role_name", administrator.role_type_id);
            return View(administrator);
        }


        // POST: Administrators1/Delete/5
         [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {

Controllers/CampusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentFinanceSupport.Models;

namespace StudentFinanceSupport.Controllers
{
     [Authorize(Roles = "Admin")]
    public class CampusController : BaseController
    {
        private StudentRegistrationsModel db = new StudentRegistrationsModel();

        // GET: Campus
        public ActionResult Index()
        {
            return View(db.Campus.ToList());
        }

        // GET: Campus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campus campus = db.Campus.Find(id);
            if (campus == null)
            {
                return HttpNotFound();
            }
            return View(campus);
        }

        // GET: Campus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Campus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_campus,campus_name")] Campus campus)
        {
            if (ModelState.IsValid)
            {
                db.Campus.Add(campus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(campus);
        }

        // GET: Campus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campus campus = db.Campus.Find(id);
            if (campus == null)
            {
                return HttpNotFound();
            }
            return View(campus);
        }

        // POST: Campus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_campus,campus_name")] Campus campus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(campus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(campus);
        }

        // GET: Campus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campus campus = db.Campus.Find(id);
            if (campus == null)
            {
                return HttpNotFound();
            }
            return View(campus);
        }

        // POST: Campus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Campus campus = db.Campus.Find(id);
            db.Campus.Remove(campus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentFinanceSupport.Models;

namespace StudentFinanceSupport.Controllers
{
     [Authorize(Roles = "Admin")]
    public class CoursesController : Controller
    {
        private StudentRegistrationsModel db = new StudentRegistrationsModel();

        // GET: Courses
        public ActionResult Index()
        {
            var courses = db.Courses.Include(c => c.Faculty);
            return View(courses.ToList());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses courses = db.Courses.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            return View(courses);
        }

        // GET: Courses/Create
        public ActionResult Create()
        {
            ViewBag.id_faculty = new SelectList(db.Faculties, "id_faculty", "faculty_name");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_courses,course_name,id_faculty")] Courses courses)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(courses);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_faculty = new SelectList(db.Faculties, "id_faculty", "faculty_name", courses.id_faculty);
            return View(courses);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses courses = db.Courses.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_faculty = new SelectList(db.Faculties, "id_faculty", "faculty_name", courses.id_faculty);
            return View(courses);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_courses,course_name,id_faculty")] Courses courses)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courses).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_faculty = new SelectList(db.Faculties, "id_faculty", "faculty_name", courses.id_faculty);
            return View(courses);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses courses = db.Courses.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            return View(courses);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Courses courses = db.Courses.Find(id);
            db.Courses.Remove(courses);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Administrators/Add.cshtml
@model StudentFinanceSupport.Models.Administrator
@using StudentFinanceSupport.Helpers


@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Main_Layout_.cshtml";
}

<h2>Add</h2>
<button class="btn btn-info back_button">Back</button>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Administrator</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" , @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mobile, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                @Html.ValidationMessageFor(model => model.mobile, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            
            <div class="">
                @Html.LabelFor(model => model.role_type_id, "Additional Roles", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.DropDownList(
                "role_type_id",
                ViewBag.role_type_id as SelectList, Helpers.SelectOneSpacer,
                 new { @class = "form-control", data_placeholder = "Choose a Role..." }
                    )
                    @Html.ValidationMessageFor(model => model.role_type_id, "", new { @class = "text-danger" })
                </div>

                </div>
        </div>

        <!-- Start of password entries -->
        <div class="form-group">
            <div class="col-md-10">

                <label class="control-label col-md-4" for="send_setup">Email user to set password ?</label>
                <input id="send_setup" type="checkbox" value="false" name="send_setup" />
            </div>
        </div>
        <div id="password_wrapper" class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @type = "password", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
            <div id="password_messages"></div>


        </div>
        <div class="form-group">
            <span class="control-label col-md-2">Retype Password</span>
            <div class="col-md-10">

                @Html.Password("password_match", (string)ViewBag.password_match, new { @class = "form-control", @value = ViewBag.password_match })

            </div>
        </div>
        <!-- End of password entries -->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/pwstrength")
<script>
    $(function () {
        "use strict";
        var options = {};
        options.common = {
            onLoad: function () {
                //$('#password_messages').text('Start typing password');
            }
        };
        options.ui = {
            bootstrap2: false,
            showErrors: true
        };
        $('#Password').pwstrength(options);
    })
</script>

Views/Administrators/Admins.cshtml
@model IEnumerable<StudentFinanceSupport.Models.Administrator>

@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_Main_Layout_.cshtml";
}

<h2>Manage Admins</h2>

<p>
    <button class="btn btn-info back_button">Back</button>
    @Html.ActionLink("Create New", "Add",null, htmlAttributes: new { @class = "btn btn-success " })
    
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.RoleType.role_name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleType.role_name)
        </td>
        

        <td class="center">
            <div class="btn-group">
                @Html.ActionLink("View Details", "Details", "Administrators",
                        new { id = item.UserId },
                            htmlAttributes: new { @class = "btn btn-default " }
                          )

                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li>@Html.ActionLink("Edit Admin", "Edit", new { id = item.UserId })</li>
                    
                    <li class="divider"></li>
                    <li class="delete" data-admin_id="@item.UserId">@Html.ActionLink("Delete", "DeleteConfirmed", new { id = item.UserId })</li>
                </ul>
            </div>

        </td>

           
        
    </tr>
}

</table>
<script>
    $(document).ready(function () {
        $(".delete").click(function (e) {
            var delete_location = $('a', this).attr('href');
            e.preventDefault();
            BootstrapDialog.confirm('Are you sure you want to delete this admin?', function (result) {
                if (result) {
                    window.location = delete_location;
                }
            });

        })

    })
</script>

Views/Administrators/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Main_Layout_.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Admin Menus</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div id="dashboard_panel" class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <a href="@Url.Action("Add", "Administrators")">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-table fa-4x"></i>
                        </div>

                        <div class="col-xs-9 text-right">
                            <div class="h3">Add Admin</div>
                            <div class="small">Adds an admin to the system</div>
                        </div>

                    </div>
                </a>
            </div>


        </div>
    </div>
    
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading ">
                <a href="@Url.Action("Admins", "Administrators")">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-graduation-cap fa-4x"></i>
                        </div>

                        <div class="col-xs-9 text-right">
                            <div class="h3">List Current Admin's</div>
                            <div class="small">List system admins</div>
                        </div>

                    </div>
                </a>
            </div>

          

        </div>
    </div>
    
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <a href="@Url.Action("Create", "Faculties")">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-edit fa-4x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="h3">Add Facuilty</div>
                            <div class="small">Add a Faculty</div>
                        </div>
                    </div>
                </a>
            </div>

        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <a href="@Url.Action("Index", "Faculties")">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-edit fa-4x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="h3">Edit Facuilty</div>
                            <div class="small">Edit a Faculty</div>
                        </div>
                    </div>
                </a>
            </div>

        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <a href="@Url.Action("Create", "Campus")">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-bar-chart-o fa-4x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="h3">Add Campus</div>
                            <div class="small">Add Campus to system</div>
                        </div>
                    </div>
                </a>
            </div>
           
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <a href="@Url.Action("Index", "Campus")">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-bar-chart-o fa-4x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="h3">Edit Campus</div>
                            <div class="small">Edit a Campus</div>
                        </div>
                    </div>
                </a>
            </div>

        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading ">
                <a href="@Url.Action("Create", "Courses")">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-graduation-cap fa-4x"></i>
                        </div>

                        <div class="col-xs-9 text-right">
                            <div class="h3">Create Course</div>
                            <div class="small">Add Course to faculty</div>
                        </div>

                    </div>
                </a>
            </div>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading ">
                <a href="@Url.Action("Index", "Courses")">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-graduation-cap fa-4x"></i>
                        </div>

                        <div class="col-xs-9 text-right">
                            <div class="h3"> Edit Courses</div>
                            <div class="small">Edit a faculty course</div>
                        </div>

                    </div>
                </a>
            </div>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading ">
                <a href="@Url.Action("Index", "GrantTypes")">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-graduation-cap fa-4x"></i>
                        </div>

                        <div class="col-xs-9 text-right">
                            <div class="h3"> Edit Grant Types</div>
                            <div class="small">Edit a grant types</div>
                        </div>

                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<!-- /.row -->

<!-- /.row -->