Controllers/GrantTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentFinanceSupport.Models;

namespace StudentFinanceSupport.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GrantTypesController : BaseController
    {
        private StudentRegistrationsModel db = new StudentRegistrationsModel();

        // GET: GrantTypes
        public ActionResult Index()
        {
            return View(db.GrantTypes.ToList());
        }

        // GET: GrantTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GrantType grantType = db.GrantTypes.Find(id);
            if (grantType == null)
            {
                return HttpNotFound();
            }
            return View(grantType);
        }

        // GET: GrantTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GrantTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "grant_type_id,grant_name,grant_value,grant_description,grant_koha,system_asset")] GrantType grantType)
        {
            if (ModelState.IsValid)
            {
                db.GrantTypes.Add(grantType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(grantType);
        }

        // GET: GrantTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GrantType grantType = db.GrantTypes.Find(id);
            if (grantType == null)
            {
                return HttpNotFound();
            }
            return View(grantType);
        }

        // POST: GrantTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "grant_type_id,grant_name,grant_value,grant_description,grant_koha,system_asset")] GrantType grantType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(grantType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(grantType);
        }

        // GET: GrantTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GrantType grantType = db.GrantTypes.Find(id);
            if (grantType == null)
            {
                return HttpNotFound();
            }
            return View(grantType);
        }

        // POST: GrantTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GrantType grantType = db.GrantTypes.Find(id);
            db.GrantTypes.Remove(grantType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/GrantTypes/Create.cshtml
@model StudentFinanceSupport.Models.GrantType

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Main_Layout_.cshtml";
}

<h2>Create</h2>
<button class="btn btn-info back_button">Back</button>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GrantType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.grant_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.grant_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.grant_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.grant_value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.grant_value)
                    @Html.ValidationMessageFor(model => model.grant_value, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.grant_description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.grant_description)
                    @Html.ValidationMessageFor(model => model.grant_description, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.grant_koha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.grant_koha)
                    @Html.ValidationMessageFor(model => model.grant_koha, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.system_asset, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.system_asset)
                    @Html.ValidationMessageFor(model => model.system_asset, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/GrantTypes/Delete.cshtml
@model StudentFinanceSupport.Models.GrantType

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Main_Layout_.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GrantType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.grant_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grant_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.grant_value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grant_value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.grant_description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grant_description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.grant_koha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grant_koha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.system_asset)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.system_asset)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/GrantTypes/Details.cshtml
@model StudentFinanceSupport.Models.GrantType

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Main_Layout_.cshtml";
}

<h2>Details</h2>
<button class="btn btn-info back_button">Back</button>
<div>
    <h4>GrantType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.grant_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grant_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.grant_value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grant_value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.grant_description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grant_description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.grant_koha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grant_koha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.system_asset)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.system_asset)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.grant_type_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/GrantTypes/Edit.cshtml
@model StudentFinanceSupport.Models.GrantType

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Main_Layout_.cshtml";
}

<h2>Edit</h2>
<button class="btn btn-info back_button">Back</button>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GrantType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.grant_type_id)

        <div class="form-group">
            @Html.LabelFor(model => model.grant_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.grant_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.grant_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.grant_value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.grant_value)
                    @Html.ValidationMessageFor(model => model.grant_value, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.grant_description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.grant_description)
                    @Html.ValidationMessageFor(model => model.grant_description, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.grant_koha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.grant_koha)
                    @Html.ValidationMessageFor(model => model.grant_koha, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.system_asset, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.system_asset)
                    @Html.ValidationMessageFor(model => model.system_asset, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/GrantTypes/Index.cshtml
@model IEnumerable<StudentFinanceSupport.Models.GrantType>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Main_Layout_.cshtml";
}

<h2>Edit Grant Types</h2>

<p>
    <button class="btn btn-info back_button">Back</button>
    @Html.ActionLink("Create New", "Create", "GrantTypes", htmlAttributes: new { @class = "btn btn-success " })

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.grant_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.grant_value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.grant_description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.grant_koha)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.grant_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.grant_value)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.grant_description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.grant_koha)
        </td>
       
        <td>
 
            @Html.ActionLink("Edit Grant Type", "Edit", "GrantTypes",
                    new { id = item.grant_type_id },
                            htmlAttributes: new { @class = "btn btn-default " }
                          )
        </td>
    </tr>
}

</table>