Controllers/CampusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentFinanceSupport.Models;

namespace StudentFinanceSupport.Controllers
{
     [Authorize(Roles = "Admin")]
    public class CampusController : BaseController
    {
        private StudentRegistrationsModel db = new StudentRegistrationsModel();

        // GET: Campus
        public ActionResult Index()
        {
            return View(db.Campus.ToList());
        }

        // GET: Campus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campus campus = db.Campus.Find(id);
            if (campus == null)
            {
                return HttpNotFound();
            }
            return View(campus);
        }

        // GET: Campus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Campus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_campus,campus_name")] Campus campus)
        {
            if (ModelState.IsValid)
            {
                db.Campus.Add(campus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(campus);
        }

        // GET: Campus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campus campus = db.Campus.Find(id);
            if (campus == null)
            {
                return HttpNotFound();
            }
            return View(campus);
        }

        // POST: Campus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_campus,campus_name")] Campus campus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(campus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(campus);
        }

        // GET: Campus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campus campus = db.Campus.Find(id);
            if (campus == null)
            {
                return HttpNotFound();
            }
            return View(campus);
        }

        // POST: Campus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Campus campus = db.Campus.Find(id);
            db.Campus.Remove(campus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentFinanceSupport.Models;

namespace StudentFinanceSupport.Controllers
{
     [Authorize(Roles = "Admin")]
    public class CoursesController : Controller
    {
        private StudentRegistrationsModel db = new StudentRegistrationsModel();

        // GET: Courses
        public ActionResult Index()
        {
            var courses = db.Courses.Include(c => c.Faculty);
            return View(courses.ToList());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses courses = db.Courses.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            return View(courses);
        }

        // GET: Courses/Create
        public ActionResult Create()
        {
            ViewBag.id_faculty = new SelectList(db.Faculties, "id_faculty", "faculty_name");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_courses,course_name,id_faculty")] Courses courses)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(courses);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_faculty = new SelectList(db.Faculties, "id_faculty", "faculty_name", courses.id_faculty);
            return View(courses);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses courses = db.Courses.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_faculty = new SelectList(db.Faculties, "id_faculty", "faculty_name", courses.id_faculty);
            return View(courses);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_courses,course_name,id_faculty")] Courses courses)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courses).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_faculty = new SelectList(db.Faculties, "id_faculty", "faculty_name", courses.id_faculty);
            return View(courses);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses courses = db.Courses.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            return View(courses);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Courses courses = db.Courses.Find(id);
            db.Courses.Remove(courses);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ReportsController.cs
using StudentFinanceSupport.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentFinanceSupport.Models.functions;
using System.Globalization;

namespace StudentFinanceSupport.Controllers
{
    public class ReportsController : BaseController
    {

        public ActionResult Index()
        {
            StudentRegistrationsModel db = new StudentRegistrationsModel();

            ViewBag.Faculity = new MultiSelectList(db.Faculties, "id_faculty", "faculty_name");
            ViewBag.Campus = new MultiSelectList(db.Campus, "id_campus", "campus_name");
            ViewBag.GrantType = new MultiSelectList(db.GrantTypes, "grant_type_id", "grant_name");

            
            return View(db.StudentVouchers);
        }
        // GET: Reports
        public ActionResult ViewReport()
        {

            StudentRegistrationsModel db = new StudentRegistrationsModel();
            var result2 = from s in db.StudentVouchers select s.StudentRegistration.Faculty.faculty_name;
            

            var result =
            from s in db.StudentVouchers.Take(10)
             group s by s.DateOfIssue into g
             select new
             {
                 read_date = g.Key.Date,
                 GrantValue = g.Sum(x => x.GrantValue),
                 T2 = g.Select(x => x.GrantType),
             };

           
            return View(db.StudentVouchers.Take(10));
        }
        public ActionResult ReportFilter()
        {

            StudentRegistrationsModel db = new StudentRegistrationsModel();
            var result2 = from s in db.StudentVouchers select s.StudentRegistration.Faculty.faculty_name;


            var result =
            from s in db.StudentVouchers.Take(10)
            group s by s.DateOfIssue into g
            select new
            {
                read_date = g.Key.Date,
                GrantValue = g.Sum(x => x.GrantValue),
                T2 = g.Select(x => x.GrantType),
            };
            ViewBag.Faculity = new MultiSelectList(db.Faculties, "id_faculty", "faculty_name");
            ViewBag.Campus = new MultiSelectList(db.Campus, "id_campus", "campus_name");
            ViewBag.GrantType = new MultiSelectList(db.GrantTypes, "grant_type_id", "grant_name");
            
            return View(db.StudentVouchers.Take(10));
        }


        /*********AJAX ONLY TRIGGERS BELOW THIS POINT PUBLIC
        * @todo add token parsing for x-cross parsing security (cross site injections)
       /***********************************************************************************/
        /// <summary>
        /// Returns JSON response of all courses related to Faculty
        /// </summary>
        /// <param name="faculty">Faculity by ID</param>
        /// <returns>JSON result of id_course & course_name</returns>
        //StudentRegistration/getCourses [GET]
        public JsonResult getFilterReports(Reports theReport)
        {
          
            //build list of issue with thereport filter model been passed


            string report_type = "Year To Date";

            StudentRegistrationsModel db = new StudentRegistrationsModel();
            
            var student_grants = from student in db.StudentRegistrations 
                                 join grants in db.StudentVouchers on student.Student_ID equals grants.student_ID         
                                 select new
                                 {
                                   
                                     //GrantyType = grants.GrantType.grant_name,
                                     grant_type_id = grants.grant_type_id,
                                     //these are enabled values from grant types model
                                     grant_description_enabled = grants.GrantType.grant_description,
                                     grant_value_enabled = grants.GrantType.grant_value,
                                     grant_koha_enabled = grants.GrantType.grant_koha,

                                     //define all our returns that other filters may require
                                     Student_ID = grants.student_ID,
                                     Grant_ID = grants.id_student_vouchers,
                                     //due to cycler refrence we need to only specify data not reference to FKEY data
                                     Grant_Name = grants.GrantType.grant_name,

                                     GrantValue = grants.GrantValue,
                                     KohaFund = grants.KuhaFunds,
                                     DateOfIssue = grants.DateOfIssue,

                                     //From the students join
                                     FirstName = grants.StudentRegistration.FirstName,
                                     LastName = grants.StudentRegistration.LastName,
                                     Gender = grants.StudentRegistration.Gender,
                                     DOB = grants.StudentRegistration.DOB,
                                     faculty_name = grants.StudentRegistration.Faculty.faculty_name,
                                     faculty_id = grants.StudentRegistration.Faculty.id_faculty,
                                     campus_id = grants.StudentRegistration.Campus.id_campus,
                                     campus_name = grants.StudentRegistration.Campus.campus_name,
                                     ethnicty = grants.StudentRegistration.Main_Ethnicity
                                 };
            //apply our filters
            if (theReport.gender != null)
                student_grants = from a in student_grants where a.Gender.ToLower() == theReport.gender.ToLower() select a;

            //by age
            if (theReport.student_age != null)
            {
                DateTime birthYear = theReport.getBirthYear();

                student_grants = from a in student_grants
                               //where clause by year of student
                               where a.DOB.Year == birthYear.Year
                               select a;

            }

            if (theReport.date_type != null)
            {
                // theReport.start_date != null
                //our model will handle conversion
                DateTime theDate = theReport.getDate();

                 //DateTime theDate = new DateTime();
                 //if empty datetype
                if (String.IsNullOrEmpty(theReport.start_date)){
                    ModelState.AddModelError("start_date", "Missing date");
                }
                else
                //lets switch 
                switch(theReport.date_type.ToLower()){
                        //return results by day
                    case "day":
                        student_grants = from a in student_grants where a.DateOfIssue.Day == theDate.Day select a;
                        report_type = "Daily Report";
                        break;
                    case "week":
                        //calc between days
                        DateTime endDate = theDate;
                        endDate = endDate.AddDays(6);

                        student_grants = from a in student_grants 
                                         where a.DateOfIssue >= theDate
                                         && a.DateOfIssue < endDate
                                         select a;
                        report_type = "Weekly Report";
                        break;
                    case "month":
                        student_grants = from a in student_grants 
                                         where a.DateOfIssue.Month == theDate.Month &&
                                         a.DateOfIssue.Year == theDate.Year
                                         select a;
                        report_type = "Monthly Report";
                        break;
                    case "year":
                        student_grants = from a in student_grants 
                                         where a.DateOfIssue.Year == theDate.Year 
                                         select a;
                        report_type = "Yearly Report";
                        break;
                }
                   
            }

            if (theReport.Faculity != null)
            {
                student_grants = from a in student_grants where a.faculty_id == theReport.Faculity select a;
            }
            //filter by grant type
            if (theReport.GrantType != null)
            {
                student_grants = from a in student_grants where a.grant_type_id == theReport.GrantType select a;
            }

            if (theReport.Campus != null)
            {
                student_grants = from a in student_grants where a.campus_id == theReport.Campus select a;
            }
            //etnicity filter
            if (theReport.Ethnicity != null)
            {
                bool is_Ethnicity = false;
                List<SelectListItem> EthnicityList = Helpers.Helpers.Ethnicity();

                foreach(var Ethnicity in EthnicityList)
                    if (Ethnicity.Value == theReport.Ethnicity) //we have ethncity
                        is_Ethnicity = true;
                        //student_grants = from a in student_grants where a.e == theReport.Faculity select a;
                
                if (is_Ethnicity)
                    student_grants = from a in student_grants where a.ethnicty == theReport.Ethnicity select a;
                else
                ModelState.AddModelError("Ethnicity", "invalid Ethnicity type");
                
                //student_grants = from a in student_grants where a.faculty_id == theReport.Faculity select a;
            }
            
            //finally grab the count of actually students for other chart

Views/Shared/Template/header.cshtml
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Luke Hardiman">
    <title>@ViewBag.Title - Student Finance System</title>
    <!-- Bootstrap & Core CSS -->
    <!-- Bootstrap Core CSS & Custom CSS -->
    @Styles.Render("~/Content/core")

    <!-- Morris Charts CSS -->
    @Styles.Render("~/Content/morris")

    <!-- Custom Fonts -->
    @Styles.Render("~/Content/fontawesome")

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!--this needs to go down the bottom after devolpment-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/adminScripts")
    @Scripts.Render("~/bundles/spinner")
</head>

Views/Shared/Template/navbar.cshtml
@using StudentFinanceSupport.Helpers

<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">@Helpers.SystemName()</a>

    </div>
    @if (Helpers.UserLoggedIn())
    {
    <!-- /.navbar-header -->
        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>
                        <a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li>
                    <li>

                        <a href="@Url.Action("ChangePassword", "Administrators")"><i class="fa fa-gear fa-fw"></i> Change Password</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="@Url.Action("LogOut", "Administrators")"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->


        </ul>
    }
    <!-- /.navbar-top-links -->
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">

            <ul class="nav" id="side-menu">
                @if (Helpers.UserLoggedIn())
                {
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input id="nav_search" type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    if (Context.User.IsInRole("Admin") || Context.User.IsInRole("Advisor"))
                    { 
                    <li class="search">
                        <a href="@Url.Action("Index", "Home")"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                    </li>
                    <li class="search">
                        <a href="@Url.Action("Create", "StudentRegistration")"><i class="fa fa-table fa-fw"></i> Add Student</a>

                    </li>

                    <li class="search">
                        <a href="@Url.Action("List", "StudentRegistration")"><i class="fa fa-graduation-cap fa-fw"></i> List Students</a>
                    </li>
                    <li class="search">
                        <a href="@Url.Action("Add", "StudentVouchers")"><i class="fa fa-edit fa-fw"></i> Add Voucher</a>

                    </li>
                     <li class="search">
                        <a href="@Url.Action("Index", "StudentVouchers")"><i class="fa fa-edit fa-fw"></i> List Student Vouchers</a>

                    </li>
                    }


                    <li class="search">
                        <a href="@Url.Action("Index", "Reports")"><i class="fa fa-bar-chart-o fa-fw"></i> View Reports</a>
                    </li>


               if (Context.User.IsInRole("Admin"))
                {
                    <li class="search">
                        <a href="#"><i class="fa fa-eye-slash fa-fw"></i> Admin Menu <span class="fa arrow"></span></a>
                        
                        <!-- second sub menu start -->
                        <!--
                            @Url.Action("Index", "Administrators")
                        -->
                        <ul class="nav nav-second-level">
                            <li class="search">
                                <a href="@Url.Action("Add", "Administrators")">Add Administrators</a>
                            </li>
                            <li class="search">
                                <a href="@Url.Action("Admins", "Administrators")">List Administrators</a>
                            </li>
                            <li class="search">
                                <a href="@Url.Action("Create", "Faculties")">Add Faculty</a>
                            </li>
                            <li class="search">
                                <a href="@Url.Action("Index", "Faculties")">Edit Faculty's</a>
                            </li>
                            <li class="search">
                                <a href="@Url.Action("Create", "Campus")">Add Campus</a>
                            </li>
                            <li class="search">
                                <a href="@Url.Action("Index", "Campus")">Edit Campus</a>
                            </li>
                            <li class="search">
                                <a href="@Url.Action("Create", "Courses")">Create Course</a>
                            </li>
                            <li class="search">
                                <a href="@Url.Action("Index", "Courses")">Edit Course</a>
                            </li>
                            <li class="search">
                                <a href="@Url.Action("Index", "GrantTypes")">Edit Grant Types</a>
                            </li>
                        </ul>
                        <!-- end sub menu -->
                    </li>
                }

                    <li>
                        <a href="@Url.Action("LogOut", "Administrators")"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                }
                else
                {
                <!-- Guest User side menus-->
                    <li>
                        <a href="@Url.Action("Login", "Administrators")"><i class="fa fa-dashboard fa-fw"></i> Login System</a>
                    </li>
                }
                <!-- Public User Side menus-->
                <li>
                    <a href="@Url.Action("About", "Home")"><i class="fa fa-dashboard fa-fw"></i> About System</a>
                </li>
            </ul>

        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>